### PR TITLE
Applying RAIL-specific python project template.

### PR DESCRIPTION
**Pull request by drewoldag**
This PR update the code base to use the RAIL-specific python project template. None of the functionality should have changed.

### CODE REVIEW

**Comment by eacharles** [comment]
So, this is somehow failing to lazy-load jax.numpy, but I can't reproduce this on my desktop, even when I try to create the conda environment from scratch.

**Comment by drewoldag** [comment]
Yeah, also failed to reproduce this locally with a fresh conda env.

**Comment by eacharles** [comment]
Ok so for some reason testing that the jax.numpy lazy load worked by doing `mod.__file__` was causing a recurison loop, so I changed the test to have it do `dir(mod)` and split out the test.

**Review by eacharles — APPROVED** [review]
lgtm, thanks.

**Pull request merged**
