### PR TITLE
making the hdf5 groupname args explicit

### PR DESCRIPTION
**Pull request by hangqianjun**
## Problem & Solution Description (including issue #)
A fix to #102 

## Code Quality
- [ ] My code follows [the code style of this project](https://rail-hub.readthedocs.io/en/latest/source/contributing.html#naming-conventions)
- [ ] I have written unit tests or justified all instances of `#pragma: no cover`; in the case of a bugfix, a new test that breaks as a result of the bug has been added
- [ ] My code contains relevant comments and necessary documentation for future maintainers; the change is reflected in applicable demos/tutorials (with output cleared!) and added/updated docstrings use the [NumPy docstring format](https://numpydoc.readthedocs.io/en/latest/format.html)
- [ ] Any breaking changes, described above, are accompanied by backwards compatibility and deprecation warnings

### CODE REVIEW

**Comment by hangqianjun** [comment]
Hi @eacharles! Quick question: is `parent_groupname` the same thing as `groupname` in `ioUtils.py`?

**Comment by hangqianjun** [comment]
Hi @eacharles! Quick question: is `parent_groupname` the same thing as `groupname` in `ioUtils.py`?

**Comment by eacharles** [comment]
Sorry, just saw this.   I’m not sure off-hand..On Sep 13, 2024, at 7:38 AM, hangqianjun ***@***.***> wrote:﻿
Hi @eacharles! Quick question: is parent_groupname the same thing as groupname in ioUtils.py?

**Review by JaimeRZP — COMMENTED** [review]
LGTM

**Review by JaimeRZP — APPROVED** [review]

**Comment by hangqianjun** [comment]
> Sorry, just saw this.   I’m not sure off-hand..On Sep 13, 2024, at 7:38 AM, hangqianjun ***@***.***> wrote:﻿ Hi @eacharles! Quick question: is parent_groupname the same thing as groupname in ioUtils.py? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

Okay, leaving these names as they are. May come back in the future to make them consistent if they are refering to the same thing...

**Pull request merged**
