### PR TITLE
9 change iterate functions to work with mpi

### PR DESCRIPTION
**Pull request by joselotl**

### CODE REVIEW

**Comment by eacharles** [comment]
Hi @joselotl , thanks for making these changes.  Can you modify the test scripts so that these lines get tested.

**Review by eacharles — COMMENTED** [review]
Overall the changes look good.   I'm just going to ask if you could tweak the tests so that the new lines either all get exectued or have #pragma: no cover around them.   
I know it is annoying, but having the tests have 100% coverage help make it easier to keep the package working in the long run.

**Comment by joselotl** [comment]
Thank you, once I learn how do tests work, I will write them both here and in ceci.

**Comment by joselotl** [comment]
@eacharles I modified the new functions in ioUtils.py so that they are tested with the test funcions previously written. I think it is  ready to merge.

**Pull request merged**
